RegisterNetEvent('gumenu:setspikes-S')
AddEventHandler('gumenu:setspikes-S', function(amt, tbl)
	TriggerClientEvent("gumenu:setspikes", -1, amt, tbl)
end)

RegisterNetEvent('gumenu:removespikes-S')
AddEventHandler('gumenu:removespikes-S', function(tbl)
	TriggerClientEvent("gumenu:removespikes", -1, tbl)
end)
RegisterNetEvent('gumenu:removeprops-S')
AddEventHandler('gumenu:removeprops-S', function(tbl)
	TriggerClientEvent("gumenu:removeprops", -1, tbl)
end)
RegisterNetEvent('gumenu:hospitalize-S')
AddEventHandler('gumenu:hospitalize-S', function(id)
	TriggerClientEvent("gumenu:hospitalize", id)
end)
RegisterNetEvent('gumenu:leavevehicle-S')
AddEventHandler('gumenu:leavevehicle-S', function(src)
	TriggerClientEvent("gumenu:leaveVehicle", src)
end)

lib.callback.register('gumenu:isAllowed', function(src)
    return IsPlayerAceAllowed(src, "gu.jail")
end)